export const projectStatusOptions = ['draft', 'active', 'archived']
export const assetStatusOptions = ['pending', 'processed', 'failed']
export const fieldStatusOptions = ['missing', 'extracted', 'reviewed', 'corrected', 'rejected']
export const recordStatusOptions = ['generated', 'generated_low_confidence', 'reviewed', 'approved', 'exported']
export const reviewStatusOptions = ['reviewed', 'corrected', 'rejected']
export const recordReviewStatusOptions = ['reviewed', 'approved', 'exported']
export const exportStatusOptions = ['pending', 'completed', 'failed']
export const ocrStatusOptions = ['pending', 'completed', 'failed']

export const workflowSteps = ['项目建档', '证据采集', 'OCR 识别', '字段复核', '记录复核', '项目导出']
